### ISSUE TITLE
delete unnecessary files

### ISSUE THREAD

**Issue by stevemart** [lee-zhg/VirtualHelpDesk#2]
some of the files checked in are not necessary:

- README.pdf -- minimal gain and would need to be regenerated for every change
- README_20180403.md -- this looks like a back up
- VirtualHelpDesk.mp4 -- put it up on youtube?
- manifest_bak.yml -- use manifest.yml
- minimal .travis.yml -- use travis.yml
- start_fail.log -- no need for a log

**Comment by lee-zhg** [comment]
@stevemart sorry, I did not see the comments until now. Files were removed
